gha

diff --git a/.github/workflows/ecr-push.yml b/.github/workflows/ecr-push.yml
--- a/.github/workflows/ecr-push.yml
+++ b/.github/workflows/ecr-push.yml
@@ -45,9 +45,10 @@ jobs:
           echo ${GITHUB_REF##*/}
 
       - name: main branch check 1
-        if: github.ref == 'refs/heads/main'
+        if: github.ref != 'refs/heads/main'
         run: |
-          echo "is main"
+          echo "::error::not main"
+          exit 1
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@master
