gha

diff --git a/.github/workflows/ecr-push-release.yml b/.github/workflows/ecr-push-release.yml
--- a/.github/workflows/ecr-push-release.yml
+++ b/.github/workflows/ecr-push-release.yml
@@ -7,7 +7,7 @@ on:
 
 env:
   IMAGE_TAG: release-${{ github.sha }}
-  SEM_VER_RegEx: ^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
+  SEM_VER_RegEx: ^[0-9]+\.[0-9]+\.[0-9]+$
 
 
 permissions:
@@ -34,7 +34,16 @@ jobs:
         run: |
           echo ${GITHUB_REF##*/}
 
-      - name: Semantic Versioning check
+      - name: Semantic Versioning check1
+        run: |
+          if [[ ${GITHUB_REF##*/} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo 'ok'
+          else
+            echo "::error::not Semantic Versioning"
+             exit 1
+          fi
+
+      - name: Semantic Versioning check2
         run: |
           if [[ ${GITHUB_REF##*/} =~ $SEM_VER_RegEx ]]; then
             echo 'ok'
